# Generated by Django 3.1.3 on 2020-11-23 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=32, null=True)),
                ('fileType', models.CharField(max_length=32, null=True)),
                ('location', models.CharField(max_length=32, null=True)),
                ('table', models.CharField(max_length=32, null=True)),
                ('field', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
