# Generated by Django 3.0.5 on 2020-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=32)),
                ('fileType', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('table', models.CharField(max_length=32)),
                ('field', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
