# Generated by Django 3.0.5 on 2020-11-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clsapi', '0003_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
